AWSTemplateFormatVersion: 2010-09-09
Description: Deploy a Bucket and creating DynamoDB tables with CloudFormation stack
Parameters:
  S3BucketName:
    Type: String
    Description: Name of Bucket for create
    Default: default-name
  DynamoDBName:
    Type: String
    Description: DynamoDB table name
    Default: default-lock

Outputs:
  S3Bucket:
    Description: Bucket created using this template.
    Value: !Ref S3Bucket
  DataDbName:
    Description: DynamoDB table created using this template.
    Value: !Ref DynamoDBName

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    Properties:
      Tags:
        - Key: "Environment"
          Value: "Dev"
      BucketName: !Ref S3BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  DynamoDB:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Ref DynamoDBName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
